# Generated by Django 3.0.2 on 2022-11-24 15:29

import autoslug.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField()),
                ('weight', models.DecimalField(decimal_places=1, default=1, max_digits=4, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(1)])),
                ('weight_goal', models.DecimalField(decimal_places=1, default=1, max_digits=4, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(1)])),
                ('height', models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('Goal', models.CharField(choices=[('maintain_weight', 'maintain_weight'), ('loose_weight', 'loose_weight'), ('gain_weight', 'gain_weight')], max_length=50, verbose_name='Goal')),
                ('Fitness', models.CharField(choices=[('no_exercise', 'no_exercise'), ('mild_exercise', 'mild_exercise'), ('high_exercise', 'high_exercise')], max_length=50, verbose_name='Fitness')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name of Cheese')),
                ('category', models.CharField(choices=[('breakfast', 'breakfast'), ('lunch', 'lunch'), ('dinner', 'dinner'), ('snacks', 'snacks')], default='breakfast', max_length=20, verbose_name='Category')),
                ('f_calories', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True, verbose_name='Total_Calories')),
                ('serving_size', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fat', models.DecimalField(decimal_places=2, max_digits=6)),
                ('protein', models.DecimalField(decimal_places=2, max_digits=6)),
                ('carbs', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cholestrol', models.DecimalField(decimal_places=2, max_digits=6)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
