# Generated by Django 3.0.2 on 2022-11-30 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='Fitness',
            field=models.CharField(choices=[('no_exercise', 'no_exercise'), ('mild_exercise', 'mild_exercise'), ('regular_exercise', 'regular_exercise')], max_length=50, verbose_name='Fitness'),
        ),
    ]
