# Generated by Django 3.0.2 on 2022-12-01 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homepage', '0004_auto_20221130_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
