# Generated by Django 3.0.2 on 2022-12-05 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_auto_20221205_2144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='cholestrol',
            new_name='cholesterol',
        ),
    ]
