# Generated by Django 3.0.2 on 2022-12-05 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_auto_20221205_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='modified',
        ),
        migrations.AlterField(
            model_name='food',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
