# Generated by Django 3.0.2 on 2022-12-05 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_auto_20221205_2221'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
