# Generated by Django 3.2.12 on 2022-12-14 06:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_alter_userdetails_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='Gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=50, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='height',
            field=models.IntegerField(default=120, validators=[django.core.validators.MaxValueValidator(230), django.core.validators.MinValueValidator(130)]),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='weight',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=4, validators=[django.core.validators.MaxValueValidator(160), django.core.validators.MinValueValidator(40)]),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='weight_goal',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=4, validators=[django.core.validators.MaxValueValidator(160), django.core.validators.MinValueValidator(40)]),
        ),
    ]
