# Generated by Django 3.2.12 on 2022-12-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_auto_20221214_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='f_calories',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Total_Calories'),
        ),
    ]
