# Generated by Django 3.2.12 on 2022-12-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_alter_food_f_calories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
